version: '3.8'

services:
  nestapp:
    image: anselmo07/nest-demo:latest
    build: ./
    ports:
      - '3000:3000'
    env_file:
    - .env.docker
    depends_on:
      - postgresdb 
  
  postgresdb:
    image: postgres
    volumes:
        - pgdata:/var/lib/postgresql/data
    env_file:
    - .env.docker

volumes:
  pgdata:          