version: '3.8'

services:
  
  nestapp:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env.development
    networks:
      - ecommerce-anselmo07_network

  postgresdb:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env.development

networks:
  ecommerce-anselmo07_network: # Redes definidas explícitamente
    driver: bridge

volumes:
  pgdata:
